### ISSUE TITLE
Vanilla loading screen option

### ISSUE THREAD

**Issue by RaptaG** [BumbleSoftware/Fastload#82] opened 2023-04-21 15:19 UTC
The box with the line? Make it togglable 🙏🏽

**Comment by StockiesLad** [comment] 2023-04-21 17:05
what does this even mean? What is the "box with the line" refer to?

**Comment by StockiesLad** [comment] 2023-04-21 17:05
Be more specific

**Comment by RaptaG** [comment] 2023-04-21 17:12
Sorry for not being specific enough @StockiesLad. Here's the screen I mean:
![2023-04-21_20 11 00](https://user-images.githubusercontent.com/77157639/233695584-c9a31e92-4b42-4a63-bd1d-e58d78739a80.png)

**Comment by StockiesLad** [comment] 2023-04-21 17:37
duplicate of https://github.com/BumbleSoftware/Fastload/issues/68

**Closed as completed by StockiesLad** 2023-04-21 17:37 UTC

**Comment by RaptaG** [comment] 2023-04-22 10:53
Could at least something (similar) graphic be added as an extra option?

**Comment by StockiesLad** [comment] 2023-04-22 11:42
Define "something graphic"?

**Comment by RaptaG** [comment] 2023-04-22 11:56
Maybe a progress bar or something similar to the removed screen (https://github.com/BumbleSoftware/Fastload/issues/82#issuecomment-1518115837)? @StockiesLad

**Comment by StockiesLad** [comment] 2023-04-23 08:59
The last message I wrote in #68 explains why I can't do it. https://github.com/BumbleSoftware/Fastload/issues/68#issuecomment-1501484526. I too would want a progress bar but it is hard to display progress like that.

To make it more obvious, here are the issues I'm facing:
- How would I objectively measure progress of the server actually starting. Would it be stages. Or should I be injecting my code into chunk/entity counters?
- If I were to divide it between stages (chunks, entities, tick, etc) how would I be able to smooth it out without making severe modifications to the server code. How could I guarantee it's even stable or fast?
- How would I go about sending this data in an effective way without causing a lot of thread interruptions.
- How should I go about making it? Should I multithread & risk creating concurrency issues?

Making a progress bar is very tedious and just not worth my time here. Especially considering that "Starting Session" is such a short time anyways. My time is limited and I can't spend it on this kind of stuff. I need to focus on bug fixing and code improvements. It's better if my time goes toward working on my abstractions so that I can pick up an older mod I was working on.

It's not to say that I won't try. I will play around with the code here and there and see if I get lucky.

**Comment by RaptaG** [comment] 2023-04-23 09:22
👍🏽
