### ISSUE TITLE
Stuck on 'Joining World' when connecting to a server

### ISSUE THREAD

**Issue by stantios** [BumbleSoftware/Fastload#65] opened 2023-04-06 18:45 UTC
Loader: Quilt
Quilt Loader Version: 0.18.8
QFAPI / QSL Version: QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13
Log: https://mclo.gs/qmWCxXE

Description: I tried to join a server with Fast Load but I got stuck on "Joining World", I could still see the world behind generating chunks but I was stuck on a screen. When I pressed "Cancel", I ended up on a page that said aborted. I'm thinking it could be related to https://github.com/BumbleSoftware/Fastload/issues/63 but I am not sure.

Screenshots: 
![Screen Shot 2023-04-06 at 19 35 22](https://user-images.githubusercontent.com/98621617/230467433-8c5dc3c6-e113-4b23-b97a-2af6c98fa779.png)
![image](https://user-images.githubusercontent.com/98621617/230467532-5f97bfe6-c07d-44b5-964d-940d46fbf981.png)

**Comment by cplir-c** [comment] 2023-04-07 03:11
Reproduced/can confirm

**Comment by Panda-X2** [comment] 2023-04-07 04:25
Can also confirm.

**Comment by TCL03-HCMUT** [comment] 2023-04-07 07:45
Can also confirm

**Comment by ZsoltiHUB** [comment] 2023-04-07 10:08
same here

**Comment by StockiesLad** [comment] 2023-04-07 11:40
duplicate of https://github.com/BumbleSoftware/Fastload/issues/63

**Comment by StockiesLad** [comment] 2023-04-08 12:18
Fixed

**Closed as completed by StockiesLad** 2023-04-08 12:18 UTC
Labels: bug, Fabric
